### ISSUE TITLE
Can you tel me how to use it?I don't know how to use in my hexo project.

### ISSUE THREAD

**Issue by Zhu-Pc** [knksmith57/hexo-renderer-sass#40]
I tried this way. 
```js
css('scss/app')
```

**Comment by knksmith57** [comment]
assuming you have a template file called `head.ejs` where the page `<head/>` is, call the [css helper](https://hexo.io/docs/helpers#css) as you've shown above:

```ejs
<head>
  <!-- lots more content... -->
  <%- css('scss/app') %>
</head>
```

that'll result in the helper looking up a file at `themes/<active theme>/source/scss/app.<extension>`. assuming the file is named `app.scss` or `app.sass`, and you've installed this package, that file will be processed by `node-sass`.

eg:
```scss
// themes/<active theme>/source/scss/app.scss
body {
  a.blue {
    &:link, &:visited {
      color: lightblue;
      text-decoration: underline;
    }

    &:hover, &:active {
      color: blue;
      text-decoration: none;
    }
  }
}
```

does that help?
